site_name: BPB 面板
site_url: https://git186404.github.io/BPB-Worker-Panel-CN/
repo_url: https://github.com/git186404/BPB-Worker-Panel-CN
copyright: 版权所有 &copy; BPB

use_directory_urls: true
site_dir: ../../site
extra_css:
  - stylesheet/extra.css
extra_javascript:
  - scripts/lang-switch.js

theme:
  name: material
  custom_dir: ../assets
  logo: favicon.ico
  favicon: favicon.ico
  direction: ltr
  language: zh
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换到浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到系统偏好
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - toc.integrate
    - navigation.tracking

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

extra:
  alternate:
    - name: English
      lang: en
      link: /BPB-Worker-Panel-CN/en/
    - name: فارسی
      lang: fa
      link: /BPB-Worker-Panel-CN/fa/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bia-pain-bache/BPB-Worker-Panel
      name: 源代码

plugins:
  - search

nav:
  - 首页: index.md
  - 安装教程:
    - 安装向导: installation/wizard.md
    - 手动安装 - Pages: installation/pages-manual.md
    - 手动安装 - Workers: installation/workers-manual.md
  - 设置配置:
    - 配置概览: configuration/index.md
    - 常规设置: configuration/common.md
    - VLESS - Trojan: configuration/vless-trojan.md 
    - 分片 (Fragment): configuration/fragment.md
    - Warp 常规: configuration/warp.md
    - Warp PRO: configuration/warp-pro.md
    - 路由规则: configuration/routing-rules.md
  - 使用说明:
    - 使用概览: usage/index.md
    - 普通使用: usage/normal.md
    - 分片使用: usage/fragment.md
    - Warp 使用: usage/warp.md
    - Warp PRO 使用: usage/warp-pro.md
    - 我的 IP: usage/my-ip.md
  - 常见问题: faq.md
